### ISSUE TITLE
indexer and vpn

### ISSUE THREAD

**Issue by PaulZhemanov** [FuelLabs/fuel-indexer#1264]
Hi, as it turns out, my indexer reacts to vpn in a very unambiguous way. It only works with vpn enabled. I recorded an interesting  [video](https://www.youtube.com/watch?v=bWOsQLNwhDk)

**Comment by deekerno** [comment]
@PaulZhemanov This might be outside of the scope of the indexer, but let's make sure.

Can you run `ping beta-3.fuel.network` with your VPN connected and then with your VPN disconnected?

**Comment by PaulZhemanov** [comment]
VPN disconnected:
```
ping beta-3.fuel.network
PING beta-3.fuel.network (188.114.99.224): 56 data bytes
64 bytes from 188.114.99.224: icmp_seq=0 ttl=59 time=36.182 ms
64 bytes from 188.114.99.224: icmp_seq=1 ttl=59 time=36.203 ms
64 bytes from 188.114.99.224: icmp_seq=2 ttl=59 time=36.842 ms
64 bytes from 188.114.99.224: icmp_seq=3 ttl=59 time=11.227 ms
64 bytes from 188.114.99.224: icmp_seq=4 ttl=59 time=9.788 ms
64 bytes from 188.114.99.224: icmp_seq=5 ttl=59 time=10.475 ms
64 bytes from 188.114.99.224: icmp_seq=6 ttl=59 time=7.619 ms
64 bytes from 188.114.99.224: icmp_seq=7 ttl=59 time=9.796 ms
64 bytes from 188.114.99.224: icmp_seq=8 ttl=59 time=11.068 ms
64 bytes from 188.114.99.224: icmp_seq=9 ttl=59 time=11.094 ms
64 bytes from 188.114.99.224: icmp_seq=10 ttl=59 time=10.072 ms
64 bytes from 188.114.99.224: icmp_seq=11 ttl=59 time=10.066 ms
64 bytes from 188.114.99.224: icmp_seq=12 ttl=59 time=7.757 ms
64 bytes from 188.114.99.224: icmp_seq=13 ttl=59 time=11.404 ms
64 bytes from 188.114.99.224: icmp_seq=14 ttl=59 time=6.983 ms
64 bytes from 188.114.99.224: icmp_seq=15 ttl=59 time=11.118 ms
64 bytes from 188.114.99.224: icmp_seq=16 ttl=59 time=9.713 ms
64 bytes from 188.114.99.224: icmp_seq=17 ttl=59 time=6.309 ms
64 bytes from 188.114.99.224: icmp_seq=18 ttl=59 time=10.364 ms
64 bytes from 188.114.99.224: icmp_seq=19 ttl=59 time=9.648 ms
64 bytes from 188.114.99.224: icmp_seq=20 ttl=59 time=7.639 ms
64 bytes from 188.114.99.224: icmp_seq=21 ttl=59 time=8.172 ms
64 bytes from 188.114.99.224: icmp_seq=22 ttl=59 time=7.825 ms
64 bytes from 188.114.99.224: icmp_seq=23 ttl=59 time=11.023 ms
64 bytes from 188.114.99.224: icmp_seq=24 ttl=59 time=10.713 m
```
VPN connected:
```
ping beta-3.fuel.network
PING beta-3.fuel.network (104.22.48.221): 56 data bytes
64 bytes from 104.22.48.221: icmp_seq=0 ttl=57 time=126.034 ms
64 bytes from 104.22.48.221: icmp_seq=1 ttl=57 time=140.654 ms
64 bytes from 104.22.48.221: icmp_seq=2 ttl=57 time=144.537 ms
64 bytes from 104.22.48.221: icmp_seq=3 ttl=57 time=139.986 ms
64 bytes from 104.22.48.221: icmp_seq=4 ttl=57 time=146.183 ms
64 bytes from 104.22.48.221: icmp_seq=5 ttl=57 time=142.794 ms
64 bytes from 104.22.48.221: icmp_seq=6 ttl=57 time=148.015 ms
64 bytes from 104.22.48.221: icmp_seq=7 ttl=57 time=145.680 ms
64 bytes from 104.22.48.221: icmp_seq=8 ttl=57 time=117.575 ms
64 bytes from 104.22.48.221: icmp_seq=9 ttl=57 time=116.420 ms
64 bytes from 104.22.48.221: icmp_seq=10 ttl=57 time=115.872 ms
64 bytes from 104.22.48.221: icmp_seq=11 ttl=57 time=116.290 ms
64 bytes from 104.22.48.221: icmp_seq=12 ttl=57 time=117.491 ms
64 bytes from 104.22.48.221: icmp_seq=13 ttl=57 time=117.681 ms
64 bytes from 104.22.48.221: icmp_seq=14 ttl=57 time=117.372 ms
64 bytes from 104.22.48.221: icmp_seq=15 ttl=57 time=114.086 ms
64 bytes from 104.22.48.221: icmp_seq=16 ttl=57 time=118.175 ms
64 bytes from 104.22.48.221: icmp_seq=17 ttl=57 time=117.643 ms
64 bytes from 104.22.48.221: icmp_seq=18 ttl=57 time=116.707 ms
64 bytes from 104.22.48.221: icmp_seq=19 ttl=57 time=121.498 ms
64 bytes from 104.22.48.221: icmp_seq=20 ttl=57 time=115.100 ms
64 bytes from 104.22.48.221: icmp_seq=21 ttl=57 time=114.571 ms
64 bytes from 104.22.48.221: icmp_seq=22 ttl=57 time=113.067 ms
```

**Comment by PaulZhemanov** [comment]
now I have this error when running the indexer
```
2023-08-14T13:29:08.855309Z  WARN fuel_indexer::executor: 113: No end_block specified in manifest. Indexer will run forever.
2023-08-14T13:29:10.359180Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:10.361556Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 0/10 failed attempts.
2023-08-14T13:29:10.872811Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:10.874810Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 1/10 failed attempts.
2023-08-14T13:29:11.339720Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:11.341218Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 2/10 failed attempts.
2023-08-14T13:29:11.736235Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:11.737362Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 3/10 failed attempts.
2023-08-14T13:29:12.128322Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.129590Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 4/10 failed attempts.
2023-08-14T13:29:12.607598Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.608331Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 5/10 failed attempts.
2023-08-14T13:29:12.995242Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.995792Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 6/10 failed attempts.
2023-08-14T13:29:13.450286Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:13.451517Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 7/10 failed attempts.
2023-08-14T13:29:13.837394Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:13.838954Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 8/10 failed attempts.
2023-08-14T13:29:14.240522Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:14.245132Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 9/10 failed attempts.
2023-08-14T13:29:14.635458Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:14.636418Z ERROR fuel_indexer::executor: 196: Indexer(paulzhemanov.indexer) failed after too many retries, giving up. <('.')>
```

**Comment by deekerno** [comment]
@PaulZhemanov What happened right before this? Also, do you know what block this was on?

**Comment by PaulZhemanov** [comment]
updated the contract and abi in indexer accordingly.
```
fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432 --postgres-password mysecretpassword --postgres-user postgres
2023-08-14T13:29:02.522383Z  INFO fuel_indexer::commands::run: 109: Configuration: IndexerConfig { metering_points: Some(30000000000), log_level: "info", verbose: false, local_fuel_node: false, indexer_net_config: false, fuel_node: FuelClientConfig { host: "beta-3.fuel.network", port: "80" }, web_api: WebApiConfig { host: "localhost", port: "29987", max_body_size: 5242880 }, database: PostgresConfig { user: "postgres", password: "XXXX", host: "127.0.0.1", port: "5432", database: "postgres", verbose: "false" }, metrics: false, stop_idle_indexers: false, run_migrations: true, authentication: AuthenticationConfig { enabled: false, strategy: None, jwt_secret: "XXXX", jwt_issuer: None, jwt_expiry: None }, rate_limit: RateLimitConfig { enabled: false, request_count: None, window_size: None }, replace_indexer: false, accept_sql_queries: false, node_block_page_size: 20 }
2023-08-14T13:29:02.525713Z  WARN sqlx_core::postgres::options::parse: 103: ignoring unrecognized connect parameter: verbose=false
2023-08-14T13:29:02.599341Z  INFO sqlx::postgres::notice: 157: identifier "graph_registry_graph_root_version_schema_name_schema_identifier_key" will be truncated to "graph_registry_graph_root_version_schema_name_schema_identifier"
2023-08-14T13:29:02.637118Z  INFO fuel_indexer_lib::utils: 138: Parsed SocketAddr '127.0.0.1:29987' from 'localhost:29987'
2023-08-14T13:29:07.898089Z  INFO tower_http::trace::on_request: 88: started processing request
2023-08-14T13:29:07.916911Z  INFO fuel_indexer_postgres: 602: Registered Asset(Manifest) with Version(99cce46b9ca60e55d5a4f197391a87a36bef96cf7bbe8c3ee46f88998ad16969) to Indexer(paulzhemanov.indexer).
2023-08-14T13:29:07.922327Z  INFO fuel_indexer_postgres: 602: Registered Asset(Schema) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871) to Indexer(paulzhemanov.indexer).
2023-08-14T13:29:07.924011Z  INFO fuel_indexer_schema::db::manager: 35: SchemaManager creating schema for Indexer(paulzhemanov.indexer) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871).
2023-08-14T13:29:07.981488Z  INFO fuel_indexer_postgres: 602: Registered Asset(Wasm) with Version(c0d2d0b1b259c6ea37d5277c4b8cf9fef17082cea5ea01ba18043b5b289ccd45) to Indexer(paulzhemanov.indexer).
2023-08-14T13:29:07.983550Z  INFO tower_http::trace::on_response: 254: finished processing request latency=85249 μs status=200
2023-08-14T13:29:08.679539Z  INFO fuel_indexer::service: 381: Resuming Indexer(paulzhemanov.indexer) from block 1839870
2023-08-14T13:29:08.850180Z  INFO fuel_indexer::database: 209: Database loading schema for Indexer(paulzhemanov.indexer) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871).
2023-08-14T13:29:08.854219Z  INFO fuel_indexer::executor: 106: Indexer(paulzhemanov.indexer) subscribing to Fuel node at beta-3.fuel.network:80
2023-08-14T13:29:08.855309Z  WARN fuel_indexer::executor: 113: No end_block specified in manifest. Indexer will run forever.
2023-08-14T13:29:10.359180Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:10.361556Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 0/10 failed attempts.
2023-08-14T13:29:10.872811Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:10.874810Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 1/10 failed attempts.
2023-08-14T13:29:11.339720Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:11.341218Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 2/10 failed attempts.
2023-08-14T13:29:11.736235Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:11.737362Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 3/10 failed attempts.
2023-08-14T13:29:12.128322Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.129590Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 4/10 failed attempts.
2023-08-14T13:29:12.607598Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.608331Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 5/10 failed attempts.
2023-08-14T13:29:12.995242Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:12.995792Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 6/10 failed attempts.
2023-08-14T13:29:13.450286Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:13.451517Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 7/10 failed attempts.
2023-08-14T13:29:13.837394Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:13.838954Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 8/10 failed attempts.
2023-08-14T13:29:14.240522Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:14.245132Z  WARN fuel_indexer::executor: 213: Indexer(paulzhemanov.indexer) retrying handler after 9/10 failed attempts.
2023-08-14T13:29:14.635458Z ERROR fuel_indexer::executor: 894: WasmIndexExecutor(paulzhemanov.indexer) WASM execution failed: RuntimeError: unreachable.
2023-08-14T13:29:14.636418Z ERROR fuel_indexer::executor: 196: Indexer(paulzhemanov.indexer) failed after too many retries, giving up. <('.')>
```

**Comment by deekerno** [comment]
@PaulZhemanov That's definitely odd! Do you have a link to the source for your indexer? That way we can try to replicate it on our side and see what the issue may be.

**Comment by PaulZhemanov** [comment]
of course, this is my [project](https://github.com/PaulZhemanov/Saprana-project)

**Comment by ra0x3** [comment]
@PaulZhemanov 
- Thanks for the video
- (A) I can see that your indexer stops when you turn your VPN off _while the indexer is running_
  - Meaning you turned the VPN on, started the service, it indexed data, then you turned your VPN off while the service was still running, and it froze 👌🏽 
- (B) However, are you also saying that your indexer doesn't work when you start the service, with your VPN off?
  - Meaning, you turn your VPN off, you start the service, and it freezes or fails to index blocks

- With regard to (A), when you toggle your VPN while the service is indexing, you've effectively changed the address that's connecting to the Fuel-core GraphQL client, so the end of the connection that was subscribed to the client (with the VPN address) is no longer valid (because you turned the VPN off while the service was running)
  - Which brings up my (B) question.
    - Because if the service doesn't work when you have the VPN off _from the start_, that would be odd to me

- We could add some logic that attempts to reset the Fuel-core GraphQL client connection I suppose, but I think that's rather niche 
- Apologies if I've misread/misunderstood something

**Comment by PaulZhemanov** [comment]
yes, indexer doesn't work with start when vpn is off..

**Comment by ra0x3** [comment]
@PaulZhemanov 
- Is there a particular branch on your project to use? Using `origin/master` I'm getting a super weird error after starting the service on beta-3
- Also, what indexer version are you using?

Start service
```bash
> cargo run --bin fuel-indexer -- run --run-migrations --accept-sql-queries --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --replace-indexer --block-page-size 25
```

Deploy the indexer
```bash
> forc index deploy                                                                                       
▹▹▸▹▹ ⏰ Building...                                                                                                                                                                                                Finished release [optimized] target(s) in 0.09s
▪▪▪▪▪ ✅ Build succeeded.                                                                                                                                                                                       Deploying indexer...
▪▪▪▪▪ ✅ Successfully deployed indexer.
```

Output

```bash
2023-08-14T14:46:51.140518Z  INFO fuel_indexer::commands::run: 109: Configuration: IndexerConfig { metering_points: Some(30000000000), log_level: "info", verbose: false, local_fuel_node: false, indexer_net_config: false, fuel_node: FuelClientConfig { host: "beta-3.fuel.network", port: "80" }, web_api: WebApiConfig { host: "localhost", port: "29987", max_body_size: 5242880 }, database: PostgresConfig { user: "postgres", password: "XXXX", host: "localhost", port: "5432", database: "postgres", verbose: "false" }, metrics: false, stop_idle_indexers: false, run_migrations: true, authentication: AuthenticationConfig { enabled: false, strategy: None, jwt_secret: "XXXX", jwt_issuer: None, jwt_expiry: None }, rate_limit: RateLimitConfig { enabled: false, request_count: None, window_size: None }, replace_indexer: true, accept_sql_queries: true, node_block_page_size: 25 }
2023-08-14T14:46:51.144074Z  WARN sqlx_core::postgres::options::parse: 103: ignoring unrecognized connect parameter: verbose=false
2023-08-14T14:46:51.154624Z  INFO sqlx::postgres::notice: 157: relation "_sqlx_migrations" already exists, skipping
2023-08-14T14:46:51.166019Z  INFO fuel_indexer_lib::utils: 138: Parsed SocketAddr '127.0.0.1:29987' from 'localhost:29987'
2023-08-14T14:48:25.075822Z  INFO tower_http::trace::on_request: 88: started processing request
2023-08-14T14:48:25.088176Z  INFO fuel_indexer_postgres: 602: Registered Asset(Manifest) with Version(99cce46b9ca60e55d5a4f197391a87a36bef96cf7bbe8c3ee46f88998ad16969) to Indexer(paulzhemanov.indexer).
2023-08-14T14:48:25.090766Z  INFO fuel_indexer_postgres: 602: Registered Asset(Schema) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871) to Indexer(paulzhemanov.indexer).
2023-08-14T14:48:25.091912Z  INFO fuel_indexer_schema::db::manager: 35: SchemaManager creating schema for Indexer(paulzhemanov.indexer) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871).
2023-08-14T14:48:25.194099Z  INFO fuel_indexer_postgres: 602: Registered Asset(Wasm) with Version(c52c53064b487dcad2fe295d1550cd9d44de075bfa009b1925ca800c8e4e8182) to Indexer(paulzhemanov.indexer).
2023-08-14T14:48:25.195700Z  INFO tower_http::trace::on_response: 254: finished processing request latency=119891 μs status=200
2023-08-14T14:48:25.382708Z  INFO fuel_indexer::service: 381: Resuming Indexer(paulzhemanov.indexer) from block 1839870
2023-08-14T14:48:28.917036Z  INFO fuel_indexer::database: 209: Database loading schema for Indexer(paulzhemanov.indexer) with Version(9e8da2731204e3cdb1c3ea955a13168c0a4142b836bd5faaf1215d06004bc871).
2023-08-14T14:48:28.918725Z  INFO fuel_indexer::executor: 106: Indexer(paulzhemanov.indexer) subscribing to Fuel node at beta-3.fuel.network:80
2023-08-14T14:48:28.919222Z  WARN fuel_indexer::executor: 113: No end_block specified in manifest. Indexer will run forever.
thread 'tokio-runtime-worker' panicked at 'misaligned pointer dereference: address must be a multiple of 0x10 but is 0x1089c3c18', /Users/rashad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-vm-4.0.0/src/trap/traphandlers.rs:219:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:        0x102a276f4 - std::backtrace_rs::backtrace::libunwind::trace::h35c35bd6a1eea1a3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102a276f4 - std::backtrace_rs::backtrace::trace_unsynchronized::h6e6a37fdc09ec2da
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102a276f4 - std::sys_common::backtrace::_print_fmt::h6ae2889d87a644d1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x102a276f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb75be2413dd8ceb3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102a49234 - core::fmt::rt::Argument::fmt::hfc9103857ff63de2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:        0x102a49234 - core::fmt::write::h95d50546e769656f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:        0x102a23bc4 - std::io::Write::write_fmt::hce019ca594763835
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:        0x102a27548 - std::sys_common::backtrace::_print::h15dce0f07dfee3db
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x102a27548 - std::sys_common::backtrace::print::hae7307dcada41b2a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x102a289c8 - std::panicking::default_hook::{{closure}}::h30c41986d637ef23
  10:        0x102a287d0 - std::panicking::default_hook::h81d03189ef2e7e78
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:        0x102a28e38 - std::panicking::rust_panic_with_hook::he8360f4d28da55fc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:        0x102a28d08 - std::panicking::begin_panic_handler::{{closure}}::he9e07d605072520f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
  13:        0x102a27ad4 - std::sys_common::backtrace::__rust_end_short_backtrace::he03bf52f9c1eb73a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:        0x102a28ab8 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:        0x102ad7ab4 - core::panicking::panic_nounwind_fmt::h6a635b966d82551e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:96:14
  16:        0x102ad7b30 - core::panicking::panic_nounwind::h241eff56ec55ba7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:126:5
  17:        0x102ad7c24 - core::panicking::panic_cannot_unwind::h911ff5cd61f62d63
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:188:5
  18:        0x10133d780 - wasmer_vm::trap::traphandlers::trap_handler::h6ea23e7b5f298104
                               at /Users/rashad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-vm-4.0.0/src/trap/traphandlers.rs:192:9
  19:        0x18b7702a4 - _OSAtomicTestAndClearBarrier
thread caused non-unwinding panic. aborting.
[1]    28933 abort      cargo run --bin fuel-indexer -- run --run-migrations --accept-sql-queries
```

**Comment by PaulZhemanov** [comment]
on master branch is my current work project, contract was wrote on beta-3, but i start indexer on latest toolchain version(0.19.4 indexer)

**Comment by ra0x3** [comment]
@PaulZhemanov Ok sweet, I'll report back in a bit. Last question, what version of `rustc` are you using? `rustc --version`

**Comment by PaulZhemanov** [comment]
```
rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by ra0x3** [comment]
@PaulZhemanov Got it. Just an FYI [you should be using `1.69.0` on beta-3](https://github.com/FuelLabs/fuel-indexer/blob/beta-3/Cargo.toml#L63). I'll get back to you when I find something 👌🏽

**Comment by PaulZhemanov** [comment]
with 1.69.0 result is same...

**Comment by ra0x3** [comment]
@PaulZhemanov Yep, I get the same result as well, just an FYI.

**Comment by ra0x3** [comment]
@PaulZhemanov 
- I see the issue(s)
- The first issue
  - Either change your contract ID in your manifest to be `fuels` namespaced (e.g., `fuels0x039393...`) or set your `contract_id` to null (e.g., `contract_id: ~`)
  - We have an issue to accept both contract ID types in the future https://github.com/FuelLabs/fuel-indexer/issues/1137
- The second issue:
  - Even if you fix that issue ☝🏽 there's another issue
  - Your schema types do not match the types coming from your Sway contract
  - How do I know? Because if I just use fake values in your indexer module (shown below) everything works
  - You should go through your contract _and make sure_ the types coming from your contract match the types in your schema

Here's the fake example I used to prove Issue 2
```rust
extern crate alloc;
use fuel_indexer_utils::prelude::*;

#[indexer(manifest = "indexer.manifest.yaml")]
pub mod indexer_index_mod {

    fn saprana_indexer_handler(block: BlockData) {
        let height = block.height;
        info!("Height: {height}");
    }

    fn handle_event_creation(data: CreateEventLog) {
        let entry = EventEntry {
            id: 1,
            owner: Address::default(),
            name: "name".to_string(),
            description: "description".to_string(),
            // image: data.event.image,
            max_participantes: 1,
            deadline: 1,
            ticket_price: 1,
            tickets_sold: 1,
            balance: 1,
        };
        info!("CreateEventLog {:#?}", entry);
        entry.save();
    }

    fn handle_buy_ticket(data: BuyTicketLog) {
        let entry = BuyTicketEntry {
            id: 2,
            event_id: 1,
            timestamp: 1,
            buyer: Identity::Address(Address::default()),
            ticket_id: 1,
            ticket_number: 1,
        };
        info!("BuyTicketLog {:#?}", entry);
        entry.save();
    }

    fn handle_claim(data: ClaimLog) {
        let entry = ClaimEntry {
            id: 3,
            event_id: 1,
            timestamp: 1,
            amount: 1,
        };
        info!("ClaimLog {:#?}", entry);
        entry.save();
    }
}
```
